#!/usr/bin/env bash
# Materialize a fork into dist/<fork>/ : a single readable lads.asm (ca65), the
# byte-exact lads.bin, a loadable C64 lads.prg, and VERIFY.txt (oracle diff result).
# Source of truth stays src/ (raw blocks + corrections + manifest); dist/ is generated.
set -eu
cd "$(dirname "$0")/.."
FORK="${1:-c64-disk}"
OUT="dist/$FORK"
mkdir -p "$OUT"

# 1. build (assembles all modules, links flat image) -- reuses the proven pipeline
bash tools/build_phase1.sh >/dev/null 2>&1

# 2. one flat, readable lads.asm = header + each module's translated ca65 in chain order
{
  echo "; ==================================================================="
  echo "; LADS -- The Second Book of Machine Language (Mansfield, 1984)"
  echo "; Fork: $FORK   |   GENERATED by tools/materialize.sh -- do not edit here."
  echo "; Source of truth: src/raw_blocks + src/corrections + tools/phase1_manifest.txt"
  echo "; Assembles byte-exact to the shipped Appendix B object code."
  echo "; ==================================================================="
  echo '.setcpu "6502"'
  echo ".org \$2AF8"
  echo
  while read -r name blocks corr; do
    case "$name" in ''|\#*) continue;; esac
    echo "; ---- module: $name ----"
    # strip the per-file auto-generated header lines, keep the body
    grep -vE '^\.(setcpu|feature|autoimport)|^; ====' "build/p1/${name}.s" || true
    echo
  done < <(grep -vE '^\s*#' tools/phase1_manifest.txt)
} > "$OUT/lads.asm"

# 3. binary (loaded image only, drop the zero BSS tail) + C64 .prg
py -3 - "$OUT" <<'PY'
import sys
out=sys.argv[1]
b=open('build/p1/lads.bin','rb').read()[:4986]
open(f'{out}/lads.bin','wb').write(b)
open(f'{out}/lads.prg','wb').write(bytes([0xF8,0x2A])+b)   # load $2AF8
PY

# 4. verification record
py -3 tools/diff_oracle.py "$OUT/lads.bin" reference/lads_c64.bin > "$OUT/VERIFY.txt" 2>&1
tail -3 "$OUT/VERIFY.txt"
echo "materialized -> $OUT/ ($(ls "$OUT" | tr '\n' ' '))"