#!/usr/bin/env bash
# Materialize a fork into dist/<fork>/ : a single readable lads.asm (ca65), the byte-exact
# lads.bin, a loadable Commodore lads.prg, and VERIFY.txt (oracle diff). Source of truth stays
# src/ (raw blocks + corrections + manifest); dist/ is generated.
#   usage: materialize.sh <fork>   e.g. c64-disk, vic-disk
set -eu
cd "$(dirname "$0")/.."
FORK="${1:-c64-disk}"
MACHINE="${FORK%%-*}"
OUT="dist/$FORK"
BUILD="build/$MACHINE"
# fork registry: C64 is the trunk (phase1 manifest); others carry a fork manifest.
if [ "$MACHINE" = "c64" ]; then MANIFEST="tools/phase1_manifest.txt"; else MANIFEST="src/forks/$MACHINE.manifest"; fi
ORACLE="reference/lads_${MACHINE}.bin"
mkdir -p "$OUT"

# 1. build this fork's modules + link, diffing vs its oracle
bash tools/build_phase1.sh "$MANIFEST" "$BUILD" "$ORACLE" >"$OUT/VERIFY.txt" 2>&1

# 2. one flat, readable lads.asm = header + each module's translated ca65 in chain order
{
  echo "; ==================================================================="
  echo "; LADS -- The Second Book of Machine Language (Mansfield, 1984)"
  echo "; Fork: $FORK   |   GENERATED by tools/materialize.sh -- do not edit here."
  echo "; Source of truth: src/raw_blocks + src/corrections + $MANIFEST"
  echo "; ==================================================================="
  echo '.setcpu "6502"'
  echo ".org \$2AF8"
  echo
  while read -r name blocks corr; do
    case "$name" in ''|\#*) continue;; esac
    echo "; ---- module: $name ----"
    grep -vE '^\.(setcpu|feature|autoimport)|^; ====' "$BUILD/${name}.s" || true
    echo
  done < <(grep -vE '^\s*#' "$MANIFEST")
} > "$OUT/lads.asm"

# 3. binary (loaded image only, drop zero BSS tail) + Commodore .prg (load $2AF8)
BUILD="$BUILD" OUT="$OUT" py -3 - <<'PY'
import os
b=open(f"{os.environ['BUILD']}/lads.bin",'rb').read()[:4986]
open(f"{os.environ['OUT']}/lads.bin",'wb').write(b)
open(f"{os.environ['OUT']}/lads.prg",'wb').write(bytes([0xF8,0x2A])+b)
PY

grep -E 'mismatches|MATCH' "$OUT/VERIFY.txt" | tail -2
echo "materialized -> $OUT/ ($(ls "$OUT" | tr '\n' ' '))"